### ISSUE TITLE
Mobs issue (tbd)

### ISSUE THREAD

**Issue by thomasrudin** [pandorabox-io/mobs_xenomorph#5]
@xenoAVP Please discuss issues with the mod here.
Can you provide an error message or simply a statement what fails to work?

**Comment by xenoAVP** [comment]
https://ibb.co/TgMNXHw 

its the link to the screen shot :D

**Comment by thomasrudin** [comment]
> https://ibb.co/TgMNXHw
> 
> its the link to the screen shot :D

rename the folder to just `mobs_xenomorph` without `-master`

**Comment by xenoAVP** [comment]
sorry for not replying quickly i dont open my mail verry oftenly...
thanks

**Comment by xenoAVP** [comment]
hi, i made a web site and a discord showcasing your mod and ery Alien mods : https://discordapp.com/channels/619731839254265865/619731839728484384             and           https://talktome2.wixsite.com/avp-minetest/mods
